server:
  port: 8082
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
#          uri: https://github.com/malki13/micro-jwt
          uri: https://github.com/malki13/datos-configuracion
          search-paths: config-data
  application:
    name: config-service
